BEGIN {
	print "/* Generated by tools/embed_help.awk. Do not edit. */"
	print "static const char " var "[] ="
}
{
	gsub(/\\/,"\\\\")
	gsub(/"/,"\\\"")
	printf "\t\"%s\\n\"\n", $0
}
END {
	print "\t;"
}
